/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Area',
        'Ext.chart.series.Line',
        'Ext.chart.interactions.PanZoom'
    ],

    viewModel: {
        type: 'mainview'
    },
    layout: 'border',

    items: [
        {
            xtype: 'gridpanel',
            collapseMode: 'mini',
            region: 'west',
            split: true,
            itemId: 'cityGrid',
            width: 300,
            collapsible: true,
            title: 'High-Low Temperature by Month',
            store: 'CityData',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'city',
                    text: 'City'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'avghigh',
                    text: 'Avg High'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'avglow',
                    text: 'Avg Low'
                }
            ]
        },
        {
            xtype: 'cartesian',
            region: 'center',
            itemId: 'cityChart',
            background: {
                fill: '#fff'
            },
            colors: [
                '#115fa6',
                '#94ae0a',
                '#a61120',
                '#ff8809',
                '#ffd13e',
                '#a61187',
                '#24ad9a',
                '#7c7474',
                '#a66111'
            ],
            insetPadding: 20,
            store: 'DetailData',
            axes: [
                {
                    type: 'category',
                    fields: [
                        'month'
                    ],
                    grid: true,
                    title: {
                        text: 'Months'
                    },
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    grid: true,
                    position: 'left',
                    title: {
                        text: 'Temperatures'
                    }
                }
            ],
            series: [
                {
                    type: 'area',
                    highlight: {
                        size: 7,
                        radius: 7
                    },
                    style: {
                        lineWidth: 1,
                        opacity: .50
                    },
                    title: [
                        'Ave Low',
                        'Ave High'
                    ],
                    xAxis: 'left',
                    xField: 'month',
                    yField: [
                        'avglow',
                        'avghigh'
                    ]
                },
                {
                    type: 'line',
                    hidden: {
                        size: 7,
                        radius: 7
                    },
                    marker: {
                        type: 'cross',
                        size: 4,
                        radius: 4,
                        'stroke-width': 0
                    },
                    title: 'High',
                    tooltip: {
                        trackMouse: true,
                        width: 160,
                        height: 25,
                        renderer: function(storeItem, item) { 
                            this.setTitle('Avg High: ' + storeItem.get('high') + ' Degrees');
                        }
                    },
                    xAxis: 'left',
                    xField: 'month',
                    yField: 'high',
                    smooth: 3
                },
                {
                    type: 'line',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    highlight: {
                        size: 7,
                        radius: 7
                    },
                    marker: {
                        type: 'circle',
                        size: 4,
                        radius: 4,
                        'stroke-width': 0
                    },
                    title: 'Low',
                    tooltip: {
                        trackMouse: true,
                        width: 160,
                        height: 25,
                        //add a custom message to the tooltip
                        renderer: function(storeItem, item) {
                            this.setTitle('Avg Low: ' + storeItem.get('low') + ' Degrees');
                        }
                    },
                    xAxis: 'left',
                    xField: 'month',
                    yField: 'low',
                    smooth: true
                }
            ],
            interactions: [
                {
                    type: 'panzoom'
                }
            ]
        }
    ]

});