/*
 * File: app/controller/AppController.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.AppController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'mainview'
        }
    },

    launch: function() {

        var store = Ext.getStore('Records'),
            mainView = this.getMainView();

        store.each(function(record) {

            var carousel = Ext.create('Ext.carousel.Carousel', {
                direction: 'horizontal'
            });

            Ext.each(record.get('values'), function(item) {

                carousel.add({
                    xtype: 'slide',
                    data: {
                        category: record.get('category'),
                        value: item
                    }
                });

            });

            mainView.add(carousel);

        });
    }

});