/*
 * File: app/store/CarDataStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.store.CarDataStore', {
    extend: 'Ext.data.Store',

    requires: [
        'CarListings.model.CarData',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore',
            autoLoad: true,
            model: 'CarListings.model.CarData',
            proxy: {
                type: 'memory',
                data: [
                    {
                        img: '2004_Porsche_911_Carrera_type_997.jpg',
                        manufacturer: 'Porsche',
                        model: '911',
                        price: 135000,
                        quality: [
                            {
                                name: 'overall',
                                rating: 1
                            },
                            {
                                name: 'mechanical',
                                rating: 4
                            },
                            {
                                name: 'powertrain',
                                rating: 2
                            },
                            {
                                name: 'body',
                                rating: 4
                            },
                            {
                                name: 'interior',
                                rating: 3
                            },
                            {
                                name: 'accessories',
                                rating: 2
                            }
                        ],
                        wiki: 'http://en.wikipedia.org/wiki/Porsche_997'
                    },
                    {
                        img: '250px-Nissan_GT-R.jpg',
                        manufacturer: 'Nissan',
                        model: 'GT-R',
                        price: 80000,
                        quality: [
                            {
                                name: 'overall',
                                rating: 2
                            },
                            {
                                name: 'mechanical',
                                rating: 3
                            },
                            {
                                name: 'powertrain',
                                rating: 5
                            },
                            {
                                name: 'body',
                                rating: 4
                            },
                            {
                                name: 'interior',
                                rating: 2
                            },
                            {
                                name: 'accessories',
                                rating: 2
                            }
                        ],
                        wiki: 'http://en.wikipedia.org/wiki/Nissan_Gt-r'
                    },
                    {
                        img: '250px-BMW_M3_E92.jpg',
                        manufacturer: 'BMW',
                        model: 'M3',
                        price: 60500,
                        quality: [
                            {
                                name: 'overall',
                                rating: 3
                            },
                            {
                                name: 'mechanical',
                                rating: 5
                            },
                            {
                                name: 'powertrain',
                                rating: 3
                            },
                            {
                                name: 'body',
                                rating: 4
                            },
                            {
                                name: 'interior',
                                rating: 5
                            },
                            {
                                name: 'accessories',
                                rating: 3
                            }
                        ],
                        wiki: 'http://en.wikipedia.org/wiki/Bmw_m3'
                    },
                    {
                        img: '250px-Audi_S5.jpg',
                        manufacturer: 'Audi',
                        model: 'S5',
                        price: 53000,
                        quality: [
                            {
                                name: 'overall',
                                rating: 4
                            },
                            {
                                name: 'mechanical',
                                rating: 1
                            },
                            {
                                name: 'powertrain',
                                rating: 1
                            },
                            {
                                name: 'body',
                                rating: 4
                            },
                            {
                                name: 'interior',
                                rating: 1
                            },
                            {
                                name: 'accessories',
                                rating: 5
                            }
                        ],
                        wiki: 'http://en.wikipedia.org/wiki/Audi_S5#Audi_S5'
                    },
                    {
                        img: '250px-2007_Audi_TT_Coupe.jpg',
                        manufacturer: 'Audi',
                        model: 'TT',
                        price: 40000,
                        quality: [
                            {
                                name: 'overall',
                                rating: 5
                            },
                            {
                                name: 'mechanical',
                                rating: 2
                            },
                            {
                                name: 'powertrain',
                                rating: 2
                            },
                            {
                                name: 'body',
                                rating: 3
                            },
                            {
                                name: 'interior',
                                rating: 4
                            },
                            {
                                name: 'accessories',
                                rating: 1
                            }
                        ],
                        wiki: 'http://en.wikipedia.org/wiki/Audi_TT'
                    }
                ]
            }
        }, cfg)]);
    }
});