/*
 * File: app/controller/Maps.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Maps', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            map: {
                selector: 'mainview map',
                xtype: 'Ext.Map'
            }
        },

        control: {
            "mainview #icelandbutton": {
                tap: 'onCurrentTap'
            }
        }
    },

    onCurrentTap: function(button, e, eOpts) {
        var map = this.getMap();
        map.setMapOptions({
            center: new google.maps.LatLng(65, -18),
            zoom: 7
        });
    }

});