/*
 * File: app/controller/Account.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Account', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'mainview'
        },

        control: {
                "mainview #loginButton": {
                        click: 'showLogin'
                },
                "mainview #registerButton": {
                        click: 'showRegister'
                }
        }
    },

    showLogin: function(target) {

        var loginForm = Ext.create('MyApp.view.LoginForm'),
                mainView = this.getMainView();

        mainView.push({
            	xtype: "loginform",
            	title: "Login"
        });

    },

    showRegister: function(target) {

        var registerForm = Ext.create('MyApp.view.RegisterForm'),
                mainView = this.getMainView();

        mainView.push({
                xtype: "registerform",
                title: "Register"
        });

    }

});