/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.Container',
    alias: 'widget.mainview',

    config: {
        layout: {
            type: 'hbox'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'App'
            },
            {
                xtype: 'container',
                flex: 1,
                style: 'background-color: #ddf;',
                ui: 'dark',
                items: [
                    {
                        xtype: 'button',
                        margin: 10,
                        text: 'Menu item 1'
                    },
                    {
                        xtype: 'button',
                        margin: 10,
                        text: 'Menu item 2'
                    },
                    {
                        xtype: 'button',
                        margin: 10,
                        text: 'Menu item 3'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 3,
                items: [
                    {
                        xtype: 'label',
                        centered: true,
                        html: 'Content'
                    }
                ]
            }
        ]
    }

});