/*
 * File: app/store/Tasks.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TasksList.store.Tasks', {
    extend: 'Ext.data.Store',

    requires: [
        'TasksList.model.Task',
        'Ext.util.Sorter'
    ],

    config: {
        data: [
            {
                description: 'Sing a song',
                priority: 'Low',
                dueDate: '1/10/2013'
            },
            {
                description: 'Give every Sencha employee $1000',
                priority: 'High',
                dueDate: '2/01/2013'
            },
            {
                description: 'Save the world',
                priority: 'High',
                dueDate: '3/12/2013'
            },
            {
                description: 'Start composting',
                priority: 'Normal',
                dueDate: '4/24/2013'
            },
            {
                description: 'Make a convincing Mona Lisa fake',
                priority: 'Low',
                dueDate: null
            }
        ],
        model: 'TasksList.model.Task',
        storeId: 'Tasks',
        sorters: {
            sorterFn: function(first, second) {
                // Completed goes last
                if (first.get('completed') && !second.get('completed')) {
                    return 1;
                } else if (!first.get('completed') && second.get('completed')) {
                    return -1;
                }

                // And then date
                if (first.get('dueDate') && !second.get('dueDate')) {
                    return -1;
                } else if (!first.get('dueDate') && second.get('dueDate')) {
                    return 1;
                }
                return (first.get('dueDate') > second.get('dueDate') ? 1 : -1);
            }
        }
    }
});