/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.view.Main', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.main',

    requires: [
        'CarListings.view.MainViewModel',
        'CarListings.view.MainViewController',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom'
    ],

    controller: 'main',
    viewModel: {
        type: 'main'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            width: 600,
            title: 'Car Listings',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    itemId: 'carGrid',
                    forceFit: true,
                    store: 'CarDataStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'manufacturer',
                            text: 'Manufacturer'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'model',
                            text: 'Model'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'price',
                            text: 'Price'
                        },
                        {
                            xtype: 'templatecolumn',
                            tpl: [
                                '<a href="{wiki}">{wiki}</a>'
                            ],
                            dataIndex: 'wiki',
                            text: 'Wiki'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'img',
                            text: 'Img'
                        }
                    ],
                    listeners: {
                        select: 'onCarGridSelect'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'centerPanel',
            layout: 'border',
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    split: true,
                    reference: 'detailPanel',
                    itemId: 'detailPanel',
                    tpl: [
                        '<div style="padding: 10px">',
                        '    <img src="resources/images/{img}" style="float: right; border: 1px solid #999" />',
                        '    <b>Manufacturer</b>: {manufacturer}<br>',
                        '    <b>Model</b>: <a href="{wiki}" target="_blank">{model}</a><br>',
                        '    <b>Price</b>: {price:usMoney}<br>',
                        '</div>'
                    ],
                    layout: 'fit',
                    title: 'Details'
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'south',
                    split: true,
                    height: 150,
                    itemId: 'chartPanel',
                    layout: 'fit',
                    title: 'Data',
                    items: [
                        {
                            xtype: 'cartesian',
                            reference: 'qualityChart',
                            colors: [
                                '#94ae0a',
                                '#115fa6',
                                '#a61120',
                                '#ff8809',
                                '#ffd13e',
                                '#a61187',
                                '#24ad9a',
                                '#7c7474',
                                '#a66111'
                            ],
                            store: 'CarChartStore',
                            axes: [
                                {
                                    type: 'category',
                                    fields: [
                                        'name'
                                    ],
                                    title: {
                                        text: 'Category'
                                    },
                                    position: 'bottom'
                                },
                                {
                                    type: 'numeric',
                                    fields: [
                                        'rating'
                                    ],
                                    majorTickSteps: 4,
                                    maximum: 5,
                                    minimum: 0,
                                    title: {
                                        text: 'Score'
                                    },
                                    position: 'bottom'
                                }
                            ],
                            series: [
                                {
                                    type: 'bar',
                                    label: {
                                        display: 'insideEnd',
                                        field: 'rating',
                                        color: '#333',
                                        'text-anchor': 'middle'
                                    },
                                    xField: 'name',
                                    yField: [
                                        'rating'
                                    ]
                                }
                            ],
                            interactions: [
                                {
                                    type: 'panzoom'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});