/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'contentPanel',
            selector: '#contentPanel'
        }
    ],

    runAction: function(target) {

        // Create new model
        var model = Ext.ModelManager.create({
            id: 123,
            text: 'Hello World',
        }, 'MyApp.model.MyModel');

        // Bind model to view
        this.getContentPanel().update(model.data);


    },

    init: function(application) {
        this.control({
            "#actionButton": {
                click: this.runAction
            }
        });
    }

});
