/*
 * File: app/store/TicketStore.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TicketTracker.store.TicketStore', {
    extend: 'Ext.data.Store',
    alias: 'store.ticketStore',

    requires: [
        'TicketTracker.model.Ticket',
        'Ext.util.Sorter'
    ],

    config: {
        data: [
            {
                title: 'Improve CSS',
                status: 'Open',
                description: 'improve site css',
                importance: 4
            },
            {
                title: 'PHP scripting',
                status: 'Open',
                description: 'Perform some PHP scripting',
                importance: 2
            },
            {
                title: 'PHP Bug',
                status: 'In Progress',
                description: 'remove PHP Bug',
                importance: 1
            }
        ],
        model: 'TicketTracker.model.Ticket',
        storeId: 'ticketStore',
        sorters: {
            sorterFn: function(first, second) {
                // Completed stuff always goes last.
                if ((first.get("status") === "completed") && (second.get("status") !== "completed")) {
                    return 1;
                } else if ((first.get("status") !== "completed") && (second.get("status") === "completed")) {
                    return -1;
                }

                // Now let's sort by importance.
                if (first.get("importance") < second.get("importance")) {
                    return -1;
                } else {
                    return 1;
                }
            }
        }
    }
});