/*
 * File: app/view/Buttons.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ComponentOverview.view.Buttons', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Spacer',
        'Ext.Button',
        'Ext.SegmentedButton'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                flex: 4,
                height: '',
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: '',
                        text: 'Normal'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'round',
                        text: 'Round'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'small',
                        text: 'Small'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 4,
                height: '',
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: '',
                        ui: 'action',
                        text: 'Action'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'action-round',
                        text: 'Round'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'action-small',
                        text: 'Small'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 4,
                height: '',
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: '',
                        ui: 'decline',
                        text: 'Decline'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'decline-round',
                        text: 'Round'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'decline-small',
                        text: 'Small'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 4,
                height: '',
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: '',
                        ui: 'confirm',
                        text: 'Confirm'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'confirm-round',
                        text: 'Round'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'confirm-small',
                        text: 'Small'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 4,
                height: '',
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: '',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'segmentedbutton',
                        items: [
                            {
                                xtype: 'button',
                                text: 'Left'
                            },
                            {
                                xtype: 'button',
                                text: 'Center'
                            },
                            {
                                xtype: 'button',
                                text: 'Right'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        ui: 'forward',
                        text: 'Forward'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            }
        ]
    }

});