/*
 * File: app/controller/Records.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Records', {
    extend: 'Ext.app.Controller',

    stores: [
        'Records'
    ],

    refs: [
        {
            ref: 'detailsPanel',
            selector: '#detailsPanel'
        }
    ],

    view: function(target, record) {

        // Get detail panel via controller ref
        var details = this.getDetailsPanel();

        // Update the detail panel with the selected row's data
        details.update(record.data);


    },

    init: function(application) {
        this.control({
            "#gridPanel": {
                select: this.view
            }
        });
    }

});
