/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'MainPanel',
                    layout: {
                        type: 'border'
                    },
                    collapsed: false,
                    manageHeight: false,
                    title: '<div class=\'main-title\'>My Records</div>',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'west',
                            split: true,
                            width: 150,
                            layout: {
                                type: 'fit'
                            },
                            collapsed: false,
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'RecordGrid',
                                    forceFit: true,
                                    store: 'RemoteStore',
                                    listeners: {
                                        select: {
                                            fn: me.onRowSelect,
                                            scope: me
                                        }
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'title',
                                            text: 'Title'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            layout: {
                                type: 'fit'
                            },
                            manageHeight: false,
                            title: 'Record Details',
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'RecordDetails',
                                    tpl: [
                                        '<h1>{title}</h1>',
                                        '<p>',
                                        '    {description}',
                                        '</p>    '
                                    ],
                                    bodyPadding: '10 10 10 10'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'AddButton',
                                    text: 'Add Record'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRowSelect: function(rowmodel, record, index, eOpts) {

        // grab a reference to the detailPanel via itemId
        // the # in front of the id indicates that we would like to grab a reference by
        var details = this.child('#RecordDetails');

        // update the detailPanel with data
        // this will trigger the tpl to become updates
        details.update(record.data);

    }

});