/*
 * File: app/view/RecordForm.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RecordForm', {
    extend: 'Ext.window.Window',

    height: 292,
    width: 455,
    bodyPadding: 10,
    title: 'Edit Record',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Title',
                    name: 'title'
                },
                {
                    xtype: 'htmleditor',
                    height: 184,
                    fieldLabel: 'Description',
                    name: 'description'
                },
                {
                    xtype: 'button',
                    margin: '5 5 5 5 ',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    margin: '5 5 5 5',
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});