/*
 * File: app/view/Viewer.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Viewer', {
    extend: 'Ext.panel.Panel',

    height: 561,
    layout: {
        type: 'border'
    },
    collapsed: false,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'center',
                    split: true
                },
                {
                    xtype: 'container',
                    region: 'west',
                    split: true,
                    border: '0 1 0 0',
                    width: 212,
                    resizable: true,
                    resizeHandles: 'e'
                }
            ]
        });

        me.callParent(arguments);
    }

});