/*
 * File: app/controller/NavController.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.NavController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: '#mainView'
        },

        control: {
            "mainview #menuButton": {
                tap: 'showMenu'
            },
            "navmenu button": {
                tap: 'navigate'
            }
        }
    },

    showMenu: function(target) {

        // Get or create navigation menu
        var menu = this.menu;
        if (!menu) {
            menu = Ext.create('MyApp.view.NavMenu');
        }

        // Show menu by menu button
        menu.showBy(target);


    },

    navigate: function(button, e, eOpts) {

        var text = button.getText(),
            mainView = this.getMainView();

        switch (text) {

            case "About Us":
            mainView.push({
                xtype: "aboutpanel",
                title: text
            });        
            break;

            case "Contact Us":
            mainView.push({
                xtype: "contactpanel",
                title: text
            });
            break;

            default:
            mainView.push({
                xtype: "homepanel",
                title: text
            });

        }
    }

});