/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',

    itemId: 'mainView',
    rtl: true,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    split: false,
                    height: 150,
                    itemId: 'headerPanel',
                    collapsible: true,
                    title: 'כותרת מכלי',
                    items: [
                        {
                            xtype: 'label',
                            padding: 20,
                            text: 'RTL הוא תכונה מרכזית כאשר אפליקציה צריכה זכות לתמיכה בשפת שמאל כגון עברית'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    split: true,
                    itemId: 'centerPanel',
                    title: 'כותרת מכלי',
                    items: [
                        {
                            xtype: 'gridpanel',
                            title: 'גריד הלוח שלי',
                            store: 'Records',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'id',
                                    text: 'מספר',
                                    format: '0,000'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'title',
                                    text: 'טקסט'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'תאריך'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'boolean',
                                    text: 'בוליאני'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'leftPanel',
                    width: 200,
                    bodyPadding: 10,
                    collapsible: true,
                    title: 'כותרת מכלי',
                    items: [
                        {
                            xtype: 'button',
                            text: 'הכפתור שלי'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'east',
                    split: true,
                    itemId: 'rightPanel',
                    width: 200,
                    bodyPadding: 10,
                    collapsible: true,
                    title: 'כותרת מכלי',
                    items: [
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: '1 פריט תפריט'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: '2 פריט תפריט'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: '3 פריט תפריט'
                                    }
                                ]
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    split: false,
                    height: 150,
                    itemId: 'footerPanel',
                    collapsible: true,
                    title: 'כותרת מכלי'
                }
            ]
        });

        me.callParent(arguments);
    }

});