/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',

    itemId: 'mainView',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'leftPanel',
                    width: 250,
                    title: 'Left'
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'centerPanel',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            split: true,
                            itemId: 'rightPanel',
                            title: 'Top'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'south',
                            split: true,
                            height: 150,
                            itemId: 'bottomPanel',
                            title: 'Bottom'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});