/*
 * File: app/view/FormPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CascadingSelect.view.FormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formpanel',

    config: {
        items: [
            {
                xtype: 'fieldset',
                id: 'fieldset',
                title: 'Choose a car!',
                items: [
                    {
                        xtype: 'selectfield',
                        id: 'makerField',
                        label: 'Maker',
                        usePicker: true
                    },
                    {
                        xtype: 'selectfield',
                        id: 'seriesField',
                        label: 'Series',
                        usePicker: true
                    },
                    {
                        xtype: 'selectfield',
                        id: 'modelField',
                        label: 'Model',
                        usePicker: true
                    },
                    {
                        xtype: 'button',
                        id: 'doneButton',
                        margin: 10,
                        text: 'Nice choice!'
                    }
                ]
            }
        ]
    }

});