/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginform',

    height: 200,
    itemId: 'loginForm',
    shrinkWrap: 3,
    manageHeight: false,
    title: 'Login',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'form',
                    bodyPadding: 20,
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 20 0',
                            fieldLabel: 'Username',
                            labelAlign: 'right',
                            msgTarget: 'title',
                            name: 'identity',
                            allowBlank: false,
                            blankText: 'Enter your Username.',
                            regexText: 'Enter your username.'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10 0',
                            fieldLabel: 'Password',
                            labelAlign: 'right',
                            msgTarget: 'title',
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false,
                            blankText: 'Enter your password.'
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'loginButton',
                            margin: '0 15 0 0',
                            scale: 'medium',
                            text: 'Login'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});