/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'htmlEditor',
            selector: '#center htmleditor'
        },
        {
            ref: 'previewPane',
            selector: '#mainView #previewPane'
        },
        {
            ref: 'htmlWindow',
            selector: 'window#htmlWindow'
        },
        {
            ref: 'submitButton',
            selector: 'button#submitButton'
        }
    ],

    init: function(application) {
        Ext.create("MyApp.view.HtmlWindow");

        this.control({
            "button[action=reset]": {
                click: this.reset
            },
            "button[action=preview]": {
                click: this.preview
            },
            "button[action=submit]": {
                click: this.submit
            },
            "button[action=resetPreview]": {
                click: this.resetPreview   
            }
        })
    },

    submit: function(evt) {
        var me = this,
            htmlEditor = me.getHtmlEditor(),
            text = htmlEditor.getValue(),
            htmlWindow = me.getHtmlWindow();

        //upfdate the text in the window	
        htmlWindow.update(text);

        //show the window
        htmlWindow.show();

        //now clear the editor and preview values
        this.reset(evt);
        this.resetPreview(evt);
    },

    reset: function(evt) {
        var me = this,
            previewPane = me.getPreviewPane(),       
            htmlEditor = me.getHtmlEditor(),
            text = htmlEditor.getValue();

        //clear the html editor
        htmlEditor.setValue();

        //clear the preview pane
        me.resetPreview(evt);	
    },

    preview: function(evt) {
        var me = this,
            previewPane = me.getPreviewPane(),       
            htmlEditor = me.getHtmlEditor(),
            text = htmlEditor.getValue();

        //update will append new text without
        //removing the previoiusly entered text.
        previewPane.update(text);	


    },

    resetPreview: function(evt) {
        var me = this,
            previewPane = me.getPreviewPane();

        //clear the text in the preview pane
        previewPane.update();
    }

});
