/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'cityChart',
            selector: 'chart#cityChart'
        },
        {
            ref: 'cityGrid',
            selector: 'grid#cityGrid'
        }
    ],

    selectCity: function(rowmodel, record, index, eOpts) {
        var chart = this.getCityChart();

        chart.getStore().loadData(record.data.chartdata);
    },

    onLaunch: function() {
        this.loadData();
    },

    loadData: function() {
        var me = this,
            cityGrid = this.getCityGrid(),
            cityChart = this.getCityChart();

        //load the grid data and setup a callback to ensure our timing is correct
        this.getCityGrid().getStore().load({
            scope: this,

            //in the callback, we'll select the first grid row that will fire the select event
            callback: function(records, operation, success) {
        		me.getCityGrid().getSelectionModel().select(0, false, false);
            }
        });
    },

    init: function(application) {
        this.control({
            "grid[itemId=cityGrid]": {
                select: this.selectCity
            }
        });
    }

});
