/*
 * File: app/view/FieldsAndRadios.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ComponentOverview.view.FieldsAndRadios', {
    extend: 'Ext.Container',
    alias: 'widget.fieldsandradios',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.field.Email',
        'Ext.field.Url',
        'Ext.field.Spinner',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.TextArea',
        'Ext.field.Radio'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                title: 'Fields',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        required: true
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Password'
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'urlfield',
                        label: 'URL',
                        placeHolder: 'http://example.com'
                    },
                    {
                        xtype: 'spinnerfield',
                        label: 'Spinner'
                    },
                    {
                        xtype: 'checkboxfield',
                        label: 'Checkbox'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Select',
                        value: null,
                        options: [
                            {
                                text: 'First Option',
                                value: 'firstOption'
                            },
                            {
                                text: 'Second Option',
                                value: 'secondOption'
                            },
                            {
                                text: 'Third Option',
                                value: 'thirdOption'
                            }
                        ]
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Date',
                        value: {
                            year: 2014,
                            month: 1,
                            day: 10
                        },
                        placeHolder: 'mm/dd/yyyy'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Text Area'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Radio',
                items: [
                    {
                        xtype: 'radiofield',
                        label: 'Option 1',
                        name: 'options'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Option 2',
                        name: 'options'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Option 3',
                        name: 'options'
                    }
                ]
            }
        ]
    }

});