/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'MyApp.view.MainViewViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Number'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            split: true,
            height: 200,
            itemId: 'headerPanel',
            layout: 'fit',
            collapsible: true,
            title: 'Dashboard'
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'west',
            split: true,
            itemId: 'leftPanel',
            width: 150,
            layout: 'fit',
            collapseDirection: 'left',
            collapsible: true,
            title: 'Company Data',
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'companyGrid',
                    rowLines: false,
                    store: 'Companies',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 140,
                            dataIndex: 'company',
                            text: 'Company'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'price',
                            text: 'Price'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'revenue',
                            text: 'Revenue'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'growth',
                            text: 'Growth'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'product',
                            text: 'Product'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'market',
                            text: 'Market'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'center',
            split: true,
            itemId: 'rightPanel',
            bodyPadding: 5,
            collapseDirection: 'right',
            collapsible: true,
            title: 'Company Details',
            items: [
                {
                    xtype: 'form',
                    itemId: 'companyForm',
                    bodyPadding: 10,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            defaults: {
                                width: 240,
                                labelWidth: 90,
                                labelAlign: 'right',
                                disabled: true,
                                maxValue: 100,
                                minValue: 0,
                                enforceMaxLength: true,
                                maxLength: 5,
                                bubbleEvents: [
                                    'change'
                                ]
                            },
                            title: 'Company Details',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Company',
                                    name: 'company'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Price',
                                    name: 'price'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Revenue',
                                    name: 'revenue'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Growth',
                                    name: 'growth'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Product',
                                    name: 'product'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Market',
                                    name: 'market'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});