/*
 * File: app/view/CascadingSelect.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CascadingSelect.view.CascadingSelect', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.cascadingselect',

    requires: [
        'CascadingSelect.view.CascadingSelectViewModel',
        'CascadingSelect.view.CascadingSelectViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'cascadingselect',
    viewModel: {
        type: 'cascadingselect'
    },

    layout: {
        type: 'hbox',
        align: 'middle',
        pack: 'center'
    },
    items: [
        {
            xtype: 'form',
            width: 500,
            bodyPadding: 10,
            title: 'Select Car',
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'makerField',
                    fieldLabel: 'Make',
                    labelAlign: 'right',
                    labelWidth: 70,
                    editable: false,
                    displayField: 'value',
                    valueField: 'id',
                    listeners: {
                        change: 'onMakerFieldChange'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'seriesField',
                    fieldLabel: 'Series',
                    labelAlign: 'right',
                    labelWidth: 70,
                    editable: false,
                    displayField: 'value',
                    valueField: 'id',
                    listeners: {
                        change: 'onSeriesFieldChange'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'modelField',
                    fieldLabel: 'Model',
                    labelAlign: 'right',
                    labelWidth: 70,
                    editable: false,
                    displayField: 'value',
                    valueField: 'id',
                    listeners: {
                        change: 'onModelFieldChange'
                    }
                },
                {
                    xtype: 'container',
                    margin: '10 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            reference: 'doneButton',
                            text: 'Choose Car',
                            listeners: {
                                click: 'onDoneButtonClick'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                render: 'onFormRender'
            }
        }
    ]

});