/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'htmlEditor',
            selector: '#center htmleditor'
        }
    ],

    onReset: function(button, e, eOpts) {

        // Clear the HTML editor
        this.getHtmlEditor().setValue();
    },

    onSubmit: function(button, e, eOpts) {

        var htmlEditor = this.getHtmlEditor(),
            text = htmlEditor.getValue(),
            htmlWindow = Ext.create("MyApp.view.HtmlWindow");

        // Update the text in the window
        htmlWindow.update(text);

        // Show the window
        htmlWindow.show();

    },

    init: function(application) {
        this.control({
            "mainview #resetButton": {
                click: this.onReset
            },
            "mainview #submitButton": {
                click: this.onSubmit
            }
        });
    }

});
