/*
 * File: app/view/TicketView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TicketTracker.view.TicketView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ticketview',

    config: {
        items: [
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'nameField',
                        label: 'Name',
                        labelAlign: 'top',
                        placeHolder: 'Save the world'
                    },
                    {
                        xtype: 'sliderfield',
                        id: 'importanceSlider',
                        label: 'Importance',
                        labelAlign: 'top',
                        value: [
                            3
                        ],
                        maxValue: 5,
                        minValue: 1
                    },
                    {
                        xtype: 'selectfield',
                        id: 'statusSelect',
                        label: 'Status',
                        labelAlign: 'top'
                    },
                    {
                        xtype: 'button',
                        margin: 10,
                        ui: 'action',
                        text: 'Save'
                    }
                ]
            }
        ]
    }

});