/*
 * File: app/view/TopPanel.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TopPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.toppanel',

    requires: [
        'MyApp.view.DescriptionLabel',
        'MyApp.view.ButtonSpacer'
    ],

    config: {
        centered: false,
        scrollable: 'vertical',
        items: [
            {
                xtype: 'descriptionlabel',
                html: 'You are in an open field west of a big white house with a boarded front door. There is a small mailbox here.'
            },
            {
                xtype: 'button',
                text: 'Go up the stairs'
            },
            {
                xtype: 'myspacer'
            },
            {
                xtype: 'button',
                text: 'Open the mailbox'
            },
            {
                xtype: 'myspacer'
            },
            {
                xtype: 'button',
                text: 'Eat a cake'
            }
        ]
    }

});