/*
 * File: app/controller/NavController.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.NavController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'contentPanel',
            selector: '#contentPanel'
        }
    ],

    onLaunch: function() {

        // Init history utility
        Ext.History.init();

        // On address change, navigate to view
        Ext.History.on('change', this.navigate);

    },

    navigate: function(view) {

        //var content = this.getContentPanel();	// Get the content panel
        //active = content.down("#" + view);	// Get the active panel within card layout
        var c = Ext.getCmp("#mainViewport");
        //var cp = this.getContentPanel();
        debugger;


        // Set the active view 
        //c.setActiveItem(1);


    }

});
