/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TicketTracker.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'list',
                title: 'Tickets',
                id: 'ticketList',
                itemTpl: [
                    '<div class="tickets-list-item">',
                    '    <div class="importance importance-{importance}">{importance}</div>',
                    '    {title}: {status}',
                    '</div>'
                ],
                store: 'ticketStore',
                onItemDisclosure: true
            }
        ],
        navigationBar: {
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    id: 'addTicketButton',
                    iconCls: 'add'
                }
            ]
        }
    }

});