/*
 * File: app/store/Radar.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Radar', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Radar',
            data: [
                {
                    Name: 'Price',
                    Data: 100
                },
                {
                    Name: 'Revenue %',
                    Data: 100
                },
                {
                    Name: 'Growth %',
                    Data: 100
                },
                {
                    Name: 'Product %',
                    Data: 100
                },
                {
                    Name: 'Market %',
                    Data: 100
                }
            ],
            fields: [
                {
                    name: 'Name'
                },
                {
                    name: 'Data'
                }
            ]
        }, cfg)]);
    }
});