/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'cardStack',
            selector: 'panel#cardStack'
        },
        {
            ref: 'nextBtn',
            selector: 'button#nextBtn'
        },
        {
            ref: 'prevBtn',
            selector: 'button#prevBtn'
        },
        {
            ref: 'newCard',
            selector: 'button#newCard'
        }
    ],

    init: function(application) {
        this.control({
            "button[direction]": {
                click: this.swapCard
            },
            "button[itemId=newCard]": {
                click: this.newCard
            }
        });
    },

    swapCard: function(btn, evt) {
        var me = this,
            cardStack = me.getCardStack(),
            layout = cardStack.getLayout();

        //custome property on the button defines
        //which direction we want the layout to move
        layout[btn.direction]();

        //disable the appropriate button if we are at
        //the end or the beginning of the card stack
        me.getPrevBtn().setDisabled(!layout.getPrev());
        me.getNextBtn().setDisabled(!layout.getNext());
    },

    newCard: function(btn, evt) {
        var me = this,
            newCard = Ext.create('Ext.panel.Panel'),
            cardStack = me.getCardStack(),
            layout = cardStack.getLayout();

        //set some properties for the newly created card
        newCard.html = 'Card ' + (cardStack.items.length + 1);
        newCard.margins = '10 10 10 10';

        //add the card to the cardStack panel
        cardStack.add(newCard);

        //activate the newly created card
        layout.setActiveItem(newCard);

        //if we're at the end of the stack, we want
        //to disable the next button
        me.getNextBtn().setDisabled(!layout.getNext());
    }

});
