/*
 * File: app/controller/Navigation.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Navigation', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'contentPanel',
            selector: '#contentPanel'
        },
        {
            ref: 'menu',
            selector: '#menu'
        }
    ],

    onLaunch: function() {

        /**
        * The following code implements simple navigation by
        * using the URL hash (#) to indicate the active view
        *
        * The following values are always equal
        * hash = active menu 'itemId' = active panel 'itemId' + 'Panel'
        */

        // Use var for controller
        var ctrl = this;

        // Init the Ext history utility
        Ext.History.init();

        // Navigate on hash change
        Ext.History.on('change', function(hash) {
            ctrl.navigate(hash);
        });

        // Navigate if initial hash is provided
        var hash = window.location.hash;
        if (hash) {
            ctrl.navigate(hash);
        }

    },

    navigate: function(id) {

        // Remove # from id if present
        if (id[0] == '#') id = id.slice(1);

        // Get views
        var menu = this.getMenu(),
            content = this.getContentPanel();

        // Set active view
        content.layout.setActiveItem(id + 'Panel');

        // Set menu and page title
        // Iterate through each menu item
        this.getMenu().items.each(function(item) {

            // Active
            if (item.href == '#' + id) {
                // Disable
                item.disable();
                // Set page title to menu item text
                window.document.title = item.text;
            }

            // Inactive
            else {
                item.enable();
            }

        });

    }

});
