/*
 * File: app/store/People.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.People', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Person',
        'Ext.data.proxy.Memory',
        'Ext.util.Sorter'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                id: 1,
                firstName: 'Tommy',
                lastName: 'Maintz'
            },
            {
                id: 2,
                firstName: 'Rob',
                lastName: 'Dougan'
            },
            {
                id: 3,
                firstName: 'Ed',
                lastName: 'Avins'
            },
            {
                id: 4,
                firstName: 'Jamie',
                lastName: 'Avins'
            },
            {
                id: 5,
                firstName: 'Dave',
                lastName: 'Dougan'
            },
            {
                id: 6,
                firstName: 'Abraham',
                lastName: 'Elias'
            },
            {
                id: 7,
                firstName: 'Jacky',
                lastName: 'Ngyuyen'
            },
            {
                id: 8,
                firstName: 'Jay',
                lastName: 'Ngyuyen'
            },
            {
                id: 9,
                firstName: 'Jay',
                lastName: 'Robinson'
            },
            {
                id: 10,
                firstName: 'Rob',
                lastName: 'Avins'
            },
            {
                id: 11,
                firstName: 'Ed',
                lastName: 'Dougan'
            },
            {
                id: 12,
                firstName: 'Jamie',
                lastName: 'Poulden'
            },
            {
                id: 13,
                firstName: 'Dave',
                lastName: 'Spencer'
            },
            {
                id: 14,
                firstName: 'Abraham',
                lastName: 'Avins'
            },
            {
                id: 15,
                firstName: 'Jacky',
                lastName: 'Avins'
            },
            {
                id: 16,
                firstName: 'Rob',
                lastName: 'Kaneda'
            },
            {
                id: 17,
                firstName: 'Ed',
                lastName: 'Elias'
            },
            {
                id: 18,
                firstName: 'Tommy',
                lastName: 'Dougan'
            },
            {
                id: 19,
                firstName: 'Rob',
                lastName: 'Robinson'
            }
        ],
        groupField: 'lastName',
        model: 'MyApp.model.Person',
        storeId: 'People',
        proxy: {
            type: 'memory'
        },
        sorters: {
            property: 'lastName'
        }
    }
});