/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginform',

    requires: [
        'MyApp.view.LoginFormViewModel',
        'MyApp.view.LoginFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'loginform',
    viewModel: {
        type: 'loginform'
    },
    height: 200,
    shrinkWrap: 3,
    manageHeight: false,
    title: 'Login',
    modal: true,

    items: [
        {
            xtype: 'form',
            bodyPadding: 20,
            items: [
                {
                    xtype: 'textfield',
                    margin: '0 0 20 0',
                    fieldLabel: 'Username',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    name: 'identity',
                    allowBlank: false,
                    blankText: 'Enter your Username.',
                    regexText: 'Enter your username.'
                },
                {
                    xtype: 'textfield',
                    margin: '0 0 10 0',
                    fieldLabel: 'Password',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    name: 'password',
                    inputType: 'password',
                    allowBlank: false,
                    blankText: 'Enter your password.'
                },
                {
                    xtype: 'button',
                    formBind: true,
                    margin: '0 15 0 0',
                    scale: 'medium',
                    text: 'Login',
                    listeners: {
                        click: 'onLoginButtonClick'
                    }
                }
            ]
        }
    ]

});