/*
 * File: app/view/MainViewViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainview',

    onLoginButtonClick: function(button, e, eOpts) {
        var refs = this.getReferences();

        // Create new login form window
        var login = Ext.create('widget.loginform', {
            loginPanel: refs.loginPanel,
            logoutPanel: refs.logoutPanel
        });

        // Show window
        login.show();
    },

    onRegisterButtonClick: function(button, e, eOpts) {
        var refs = this.getReferences();

        // Create new login form window
        var register = Ext.create('widget.registerform', {
            loginPanel: refs.loginPanel,
            lougoutPanel: refs.logoutPanel
        });

        // Show window
        register.show();
    },

    onLogoutButtonClick: function(button, e, eOpts) {

    }

});
