/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CascadingSelect.view.MainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    layout: {
        align: 'middle',
        pack: 'center',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'form',
                    width: 500,
                    bodyPadding: 10,
                    title: 'Select Car',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'makerField',
                            fieldLabel: 'Make',
                            labelAlign: 'right',
                            labelWidth: 70,
                            editable: false,
                            displayField: 'value',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'seriesField',
                            fieldLabel: 'Series',
                            labelAlign: 'right',
                            labelWidth: 70,
                            editable: false,
                            displayField: 'value',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'modelField',
                            fieldLabel: 'Model',
                            labelAlign: 'right',
                            labelWidth: 70,
                            editable: false,
                            displayField: 'value',
                            valueField: 'id'
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 10 0',
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'doneButton',
                                    text: 'Choose Car'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});