/*
 * File: app/controller/RecordController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.RecordController', {
    extend: 'Ext.app.Controller',

    view: function(rowmodel, record, index, eOpts) {

        // Query the detail panel by it's ID
        var details = Ext.getCmp('DetailPanel');

        // Update the detail panel with the selected row's data
        details.update(record.data);
    },

    add: function(target) {

        // Open new window
        var window = Ext.create('MyApp.view.RecordForm');
        window.show();

    },

    edit: function(target) {
        // Get panel data
        var data = target.up('panel').data;

        // Create new edit window
        var window = Ext.create('MyApp.view.RecordForm');

        // Set form values
        var form = window.down('form').getForm();
        form.setValues(data);

        // Show window
        window.show();

    },

    save: function(target) {

        // Get values
        var form = target.up('form').getForm(),	// Form
        values = form.getValues(),			// Form values
        window = target.up('window');		// Window

        // Save data

        // Close window
        window.destroy();

        // Update views
    },

    cancelEdit: function(target) {

        // Get the window and close it
        var window = target.up("window");
        window.destroy();

    },

    delete: function(target) {

        // Confirm this delete
        Ext.MessageBox.confirm('Confirm', 'Are you sure you want to delete this record?', function() {

            // Delete record from store

            // Remove from UI


        });
    },

    init: function(application) {
        this.control({
            "#RecordGrid": {
                select: this.view
            },
            "#AddButton": {
                click: this.add
            },
            "#DetailPanel button[text=Edit]": {
                click: this.edit
            },
            "#RecordForm button[text=Save]": {
                click: this.save
            },
            "#RecordForm button[text=Cancel]": {
                click: this.cancelEdit
            },
            "#DetailPanel button[text=Delete]": {
                click: this.delete
            }
        });
    }

});
