/*
 * File: app/controller/RecordController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.RecordController', {
    extend: 'Ext.app.Controller',

    viewDetails: function(rowmodel, record, index, eOpts) {

        // Query the detail panel by it's ID
        var details = Ext.getCmp('DetailPanel');

        // Update the detail panel with the selected row's data
        details.update(record.data);
    },

    openForm: function(target) {

        // Open new window
        var window = Ext.create('MyApp.view.RecordForm');
        window.show();

    },

    closeForm: function(target) {

        // Get the window and close it
        var window = target.up("window");
        window.destroy();

    },

    saveRecord: function(target) {

        Ext.Msg.alert("Works");
    },

    init: function(application) {
        this.control({
            "#RecordGrid": {
                select: this.viewDetails
            },
            "#AddButton": {
                click: this.openForm
            },
            "#RecordForm button[text=Cancel]": {
                click: this.closeForm
            },
            "#RecordForm button[text=Save]": {
                click: this.saveRecord
            }
        });
    }

});
