/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.CardStack'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 100,
                    title: 'Header',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    direction: 'prev',
                                    itemId: 'prevBtn',
                                    text: 'Previous'
                                },
                                {
                                    xtype: 'button',
                                    direction: 'next',
                                    itemId: 'nextBtn',
                                    text: 'Next'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'newCard',
                                    text: 'New Card'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'cardstack',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }

});