/*
 * File: app/view/RedditViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RedditViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainviewport',

    onSettingsToolClick: function(tool, e, owner, eOpts) {
        var panel = Ext.create('MyApp.view.SettingsPanel');

        panel.show();
    },

    onReloadToolClick: function(tool, e, owner, eOpts) {
        Ext.getStore('redditHomepage').reload();
    }

});
