/*
 * File: app/store/DetailData.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.DetailData', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.CityData'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'DetailData',
            model: 'MyApp.model.CityData',
            data: [
                {
                    month: 'January',
                    high: 23,
                    low: 10,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'February',
                    high: 26,
                    low: 15,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'March',
                    high: 36,
                    low: 22,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'April',
                    high: 39,
                    low: 20,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'May',
                    high: 50,
                    low: 39,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'June',
                    high: 60,
                    low: 53,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'July',
                    high: 66,
                    low: 51,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'August',
                    high: 68,
                    low: 54,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'September',
                    high: 59,
                    low: 47,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'October',
                    high: 51,
                    low: 39,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'November',
                    high: 30,
                    low: 20,
                    avghigh: 24,
                    avglow: 20
                },
                {
                    month: 'December',
                    high: 25,
                    low: 16,
                    avghigh: 24,
                    avglow: 20
                }
            ]
        }, cfg)]);
    }
});