/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'MyApp.view.MainViewportViewModel',
        'MyApp.view.MainViewportViewController',
        'Ext.panel.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.button.Button'
    ],

    controller: 'mainviewport',
    viewModel: {
        type: 'mainviewport'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            manageHeight: false,
            title: 'Countdown',
            layout: {
                type: 'hbox',
                pack: 'center',
                padding: 10
            },
            items: [
                {
                    xtype: 'container',
                    html: {
                        
                    },
                    width: 700,
                    items: [
                        {
                            xtype: 'container',
                            reference: 'timerDisplay',
                            height: 45,
                            margin: '0 0 20',
                            style: {
                                'font-size': '1.5em',
                                border: '1px solid #ccc;',
                                padding: '5px',
                                'text-align': 'center'
                            }
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    flex: 1,
                                    reference: 'dateField',
                                    fieldLabel: 'Date',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'date'
                                },
                                {
                                    xtype: 'timefield',
                                    flex: 1,
                                    reference: 'timeField',
                                    margin: '0 10 0 0',
                                    fieldLabel: 'Time',
                                    labelAlign: 'right',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    reference: 'startButton',
                                    margin: '0 10 0 0',
                                    text: 'Start',
                                    listeners: {
                                        click: 'onStartButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margins: '0 10 0 0',
                                    reference: 'resetButton',
                                    disabled: true,
                                    text: 'Reset',
                                    listeners: {
                                        click: 'onResetButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});