/*
 * File: app/model/Record.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Record', {
    extend: 'Ext.data.Model',
    alias: 'model.record',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'title'
        },
        {
            name: 'description'
        },
        {
            name: 'date',
            type: 'date'
        },
        {
            name: 'isFeatured',
            type: 'boolean'
        }
    ]
});