/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    itemId: 'mainViewport',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    split: true,
                    height: 150,
                    itemId: 'northPanel',
                    title: 'North'
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    split: true,
                    itemId: 'centerPanel',
                    title: 'Center'
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'westPanel',
                    width: 150,
                    title: 'West'
                },
                {
                    xtype: 'panel',
                    region: 'east',
                    split: true,
                    itemId: 'eastPanel',
                    width: 150,
                    title: 'East'
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    split: true,
                    height: 150,
                    itemId: 'southPanel',
                    title: 'South'
                }
            ]
        });

        me.callParent(arguments);
    }

});