/*
 * File: app/controller/Locations.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Locations', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'Location'
        ],
        stores: [
            'Locations'
        ],

        refs: {
            mapView: {
                selector: 'mainview #map',
                xtype: 'Ext.Map'
            },
            mainView: {
                selector: 'mainview',
                xtype: 'Ext.navigation.View'
            },
            mapPanel: {
                selector: 'mainview #mapPanel',
                xtype: 'Ext.Panel'
            },
            addLocationButton: {
                selector: 'mainview #addLocationButton',
                xtype: 'Ext.Button'
            },
            listLocationsButton: {
                selector: 'mainview #listLocationsButton',
                xtype: 'Ext.Button'
            },
            newLocationMap: 'mainview #newLocationMap',
            newLocationForm: 'mainview #formPanel'
        },

        control: {
            "mainview #addLocationButton": {
                tap: 'onAddLocationTap'
            },
            "mainview #listPanel list": {
                disclose: 'onLocationTap'
            },
            "mainview #listLocationsButton": {
                tap: 'onListLocationsTap'
            },
            "mainview": {
                back: 'onBack',
                activate: 'onStart'
            },
            "mainview #locationTextField": {
                change: 'onNewLocationPositionChange'
            },
            "mainview #saveLocationButton": {
                tap: 'onSaveLocationButtonTap'
            }
        }
    },

    onAddLocationTap: function(button, e, eOpts) {
        this.getMainView().push({
            xtype: 'formpanel',
            title: 'New location'
        });
        
        this.hideButtons();
    },

    onLocationTap: function(list, record, target, index, e, eOpts) {
        var latitude = record.get('latitude'),    // Build the location
            longitude = record.get('longitude'),
            location = new google.maps.LatLng(latitude, longitude),
            map = this.getMapView();              // Find the map
        
        map.setMapOptions({   // Move to the center
            center: location
        });
        
        this.showButtons();
        
        this.getMainView().pop();   // Remove the pin list panel
    },

    onListLocationsTap: function(button, e, eOpts) {
        this.getMainView().push({   // Show the list panel view
            xtype: 'listpanel',
            title: 'List spot'
        });
        
        this.hideButtons();
    },

    onBack: function(navigationview, eOpts) {
        this.showButtons();
    },

    onStart: function(newActiveItem, container, oldActiveItem, eOpts) {
        this.showButtons();
    },

    onNewLocationPositionChange: function(textfield, newValue, oldValue, eOpts) {
        // Find the map
        var map = this.getNewLocationMap().getMap();
        
        // Build a marker if there isn't one
        if (!this.newLocationMapMarker) {
            this.newLocationMapMarker = new google.maps.Marker;
        }
        
        // Hide the map marker
        this.newLocationMapMarker.setMap(null);
        
        // Geocode the string
        var me = this;
        this.geocodeString(newValue, function(position) {
        
            // Move the map to the position
            map.setOptions({
                center: position,
                zoom: 15
            });
        
            // Drop a marker there
            me.newLocationMapMarker.setOptions({
                map: map,
                position: position,
                animation: google.maps.Animation.DROP
            });
        
        });
    },

    onSaveLocationButtonTap: function(button, e, eOpts) {
        var form = this.getNewLocationForm(),
            values = form.getValues(),
            store = Ext.getStore('Locations'),
            map = this.getMapView().getMap();
        
        var me = this;
        this.geocodeString(values.location, function(position) {
        
            if (position) {
        
                // Add this to the store
                store.add({
                    name: values.name,
                    description: values.description,
                    latitude: position.lat(),
                    longitude: position.lng()
                });
        
                // Drop a pin
                new google.maps.Marker({
                    position: position,
                    map: map,
                    animation: google.maps.Animation.DROP
                });
        
                // Move the map there
                map.setOptions({
                    center: position
                });
        
                // Go back to the map view
                me.getMainView().pop();
        
                // Show the navbar buttons
                me.showButtons();
        
            }
        
        });
    },

    showButtons: function() {
        var locationCount = Ext.getStore('Locations').getCount(),
            hasLocations = (locationCount != 0);
        
        this.getAddLocationButton().show();
        if (hasLocations) {
            this.getListLocationsButton().show();
        } else {
            this.getListLocationsButton().hide();
        }
    },

    hideButtons: function() {
        this.getAddLocationButton().hide();
        this.getListLocationsButton().hide();
    },

    geocodeString: function(str, callback) {
        var geocoder = new google.maps.Geocoder,
            options = { address: str };
        
        geocoder.geocode(options, function(results, status) {
            if (status == "OK") {
                callback(results[0].geometry.location);
            } else {
                callback(null);
            }
        });
    }

});